
name: Build and Test - Supported Python Versions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        version: [ "3.11", "3.12" ]
    runs-on: act-fast

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{matrix.version}}
    - name: Update apt
      run: |
        sudo apt update
    - name: Install dependencies
      run: |
        sudo apt install -y fonts-roboto ffmpeg libcairo2-dev
        PYTHONVERSION=${{matrix.version}} make venv req
    - name: Test with pytest
      run: |
        PYTHONVERSION=${{matrix.version}} make ci
    - name: Upload build artefacts
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: approval-artifacts
        path: ${{ github.workspace }}/tests/approvals/*.png
        retention-days: 2

